#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_FFI_H 1
#define HAVE_WINDOWS_H 1
#define HAVE_LOADLIBRARY 1
#define HAVE_FREELIBRARY 1
#define HAVE_GETPROCADDRESS 1
#define HAVE_CONST_FFI_STDCALL 1
#define SIGNEDNESS_OF_SIZE_T +1
#endif
